version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - '3009:3009'
    volumes:
      - '/app/node_modules'
      - './server:/app'
  nginx:
    restart: always
    image: 
      'nginx:latest'
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:3051'
    depends_on:
      - api
      - client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    volumes:
      - '/app/node_modules'
      - './client:/app'
    command: npm run start
    depends_on:
      - api
  mongo:
   image: mongo