version: '3'
services:
  test_task-nginx:
    restart: always
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3050:3050'
    depends_on:
      - test_task-api
      - test_task-client

  test_task-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3009:3009'
    volumes:
      - '/app/node_modules'
      - './server:/app'

  test_task-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - '/app/node_modules'
      - './client:/app'
    command: npm run dev

  mongo:
    image: mongo
