version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    networks:
      - shared-network
    env_file:
      - ./server/.env
    depends_on:
      - frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client/nginx:/etc/nginx/conf.d
    ports:
      - "81:80"
    networks:
      - shared-network
  mongo:
    image: mongo
networks:
  shared-network:

# version: '3'
# services:
#   mongo:
#     image: mongo
#     networks:
#       - shared-network
#   server:
#    container_name: envelop_api
#    restart: unless-stopped
#    image: nestjs-api:1.0.0
#    build:
#     context: server
#     target: production
#     dockerfile: Dockerfile
#    ports:
#      - 3009:3009
#    networks:
#      - shared-network
#    depends_on:
#      - mongo
#   client:
#     container_name: envelop_frontend
#     restart: unless-stopped
#     image: envelop_frontend:1.0.0
#     build:
#       context: client
#       dockerfile: Dockerfile
#     ports:
#       - 5137:5137
#     networks:
#       - shared-network
#     depends_on:
#       - server
# networks:
#   shared-network:
   